# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'LYSFMDBManagerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LYSFMDBManagerDemo

  target 'LYSFMDBManagerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LYSFMDBManagerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'FMDB', '~> 2.7.2'
end
